[[menu.main]]
  name = "Beranda"
  url = "/"
  weight = 10
[[menu.main]]
  name = "Titik Ba"
  url = "/pages/titik-ba/" # URL diperbarui
  weight = 20
[[menu.main]]
  name = "Ayat-Ayat Cerita"
  url = "/pages/ayat-cerita/" # URL diperbarui
  weight = 30
[[menu.main]]
  name = "Matematika Detik"
  url = "/pages/matematika-detik/" # URL diperbarui
  weight = 40
[[menu.main]]
  name = "Matematika Titik"
  url = "/pages/matematika-titik/" # URL diperbarui
  weight = 50
[[menu.main]]
  name = "Bimbel"
  url = "/pages/bimbel/" # URL diperbarui
  weight = 60
[[menu.main]]
  name = "Kamp Santri"
  url = "/pages/kamp-santri/" # URL diperbarui
  weight = 70
