# Backend untuk testing lokal, tidak perlu akun GitHub.
# Nanti bisa diubah untuk dihubungkan ke GitHub.
backend:
  name: git-gateway
  branch: main 
# Lokasi penyimpanan media/gambar yang di-upload melalui CMS
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Daftar konten yang bisa diedit
collections:
  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
