backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Halaman"
    files:
      - file: "content/sejarah.md"
        label: "Halaman Sejarah"
        name: "sejarah"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/titik-ba.md"
        label: "Halaman: Titik Ba"
        name: "halaman_titik_ba"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/ayat-cerita.md"
        label: "Halaman: Ayat-Ayat Cerita"
        name: "halaman_ayat_cerita"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/matematika-detik.md"
        label: "Halaman: Matematika Detik"
        name: "halaman_matematika_detik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/matematika-titik.md"
        label: "Halaman: Matematika Titik"
        name: "halaman_matematika_titik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/bimbel.md"
        label: "Halaman: Bimbel"
        name: "halaman_bimbel"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/kamp-santri.md"
        label: "Halaman: Kamp Santri"
        name: "halaman_kamp_santri"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }

  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: false
        options: ["Titik Ba", "Ayat-Ayat Cerita", "Matematika Detik", "Matematika Titik", "Bimbel", "Kamp Santri"]
      - label: "Isi Artikel"
        name: "body"
        widget: "markdown"
  - name: "video"
    label: "Galeri Video"
    folder: "content/video"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Video", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "YouTube Video ID", name: "youtube_id", widget: "string", hint: "Contoh: dari URL https://www.youtube.com/watch?v=dQw4w9WgXcQ, ID-nya adalah dQw4w9WgXcQ" }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
