backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Mendefinisikan editor blok yang bisa dipakai ulang
editor_blok: &block_editor
  name: "body"
  label: "Konten Halaman"
  widget: "list"
  required: false
  types:
    - name: "markdown"
      label: "Paragraf Teks"
      widget: "object"
      fields:
        - {name: "content", label: "Teks", widget: "markdown"}
    - name: "image"
      label: "Gambar"
      widget: "object"
      fields:
        - {label: "File Gambar", name: "src", widget: "image"}
        - {label: "Teks Alt (Deskripsi)", name: "alt", widget: "string"}
        - {label: "Keterangan (Caption)", name: "caption", widget: "string", required: false}
        - {label: "Ukuran Gambar", name: "size", widget: "select", options: ["Kecil", "Sedang", "Besar"], default: "Sedang"}
    - name: "youtube"
      label: "Video YouTube"
      widget: "object"
      fields:
        - {label: "ID Video YouTube", name: "id", widget: "string"}

collections:
  - name: "pengaturan"
    label: "Pengaturan Halaman"
    files:
      - file: "content/_index.md"
        label: "Halaman Beranda (Profil)"
        name: "beranda"
        fields:
          - *block_editor # Menggunakan editor blok yang sudah didefinisikan
          
  - name: "pages"
    label: "Halaman Utama"
    folder: "content/pages"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - *block_editor # Menggunakan editor blok yang sama

  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    identifier_field: "title"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal Publikasi", name: "date", widget: "datetime"}
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: false
        options: ["Titik Ba", "Ayat-Ayat Cerita", "Matematika Detik", "Matematika Titik", "Bimbel", "Kamp Santri"]
        required: false
      - *block_editor # Menggunakan editor blok yang sama
        
  - name: "video"
    label: "Galeri Video"
    folder: "content/video"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    fields:
      - { label: "Judul Video", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "YouTube Video ID", name: "youtube_id", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown", required: false}