collections:
  - name: "pages"
    label: "Halaman & Gagasan"
    files:
      - file: "content/_index.md"
        label: "Halaman Beranda (Deskripsi)"
        name: "beranda"
        fields:
          - { label: "Isi Deskripsi di Bawah Judul Utama", name: "body", widget: "markdown" }
      - file: "content/gagasan-utama.md"
        label: "Gagasan: Halaman Utama"
        name: "gagasan_utama"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-titik-ba.md"
        label: "Gagasan: Titik Ba"
        name: "gagasan_titik_ba"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-ayat-cerita.md"
        label: "Gagasan: Ayat-Ayat Cerita"
        name: "gagasan_ayat_cerita"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-matematika-detik.md"
        label: "Gagasan: Matematika Detik"
        name: "gagasan_matematika_detik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-matematika-titik.md"
        label: "Gagasan: Matematika Titik"
        name: "gagasan_matematika_titik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-bimbel.md"
        label: "Gagasan: Bimbel"
        name: "gagasan_bimbel"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-kamp-santri.md"
        label: "Gagasan: Kamp Santri"
        name: "gagasan_kamp_santri"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/titik-ba.md"
        label: "Halaman: Titik Ba"
        name: "halaman_titik_ba"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/ayat-cerita.md"
        label: "Halaman: Ayat-Ayat Cerita"
        name: "halaman_ayat_cerita"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/matematika-detik.md"
        label: "Halaman: Matematika Detik"
        name: "halaman_matematika_detik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/matematika-titik.md"
        label: "Halaman: Matematika Titik"
        name: "halaman_matematika_titik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/bimbel.md"
        label: "Halaman: Bimbel"
        name: "halaman_bimbel"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }
      - file: "content/kamp-santri.md"
        label: "Halaman: Kamp Santri"
        name: "halaman_kamp_santri"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman (di bawah jargon)", name: "body", widget: "markdown" }

  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: false
        options: ["Titik Ba", "Ayat-Ayat Cerita", "Matematika Detik", "Matematika Titik", "Bimbel", "Kamp Santri"]
      - label: "Isi Artikel"
        name: "body"
        widget: "markdown"
        editor:
          styles:
            - { label: "Rata Kiri", value: "text-left" }
            - { label: "Rata Tengah", value: "text-center" }
            - { label: "Rata Kanan", value: "text-right" }
            - { label: "Rata Kiri-Kanan (Justify)", value: "text-justify" }