backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Halaman & Gagasan"
    files:
      - file: "content/_index.md"
        label: "Halaman Beranda (Profil)"
        name: "beranda"
        fields:
          - label: "Konten Halaman"
            name: "body"
            widget: "list"
backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "pages"
    label: "Halaman & Gagasan"
    files:
      - file: "content/_index.md"
        label: "Halaman Beranda (Profil)"
        name: "beranda"
        fields:
          - name: "body"
            label: "Konten Halaman"
            widget: "list"
            types:
              - name: "markdown"
                label: "Paragraf Teks"
                widget: "markdown"
              - name: "image"
                label: "Gambar"
                widget: "object"
                fields:
                  - {label: "File Gambar", name: "src", widget: "image"}
                  - {label: "Teks Alt (Deskripsi)", name: "alt", widget: "string"}
                  - {label: "Keterangan (Caption)", name: "caption", widget: "string", required: false}
              - name: "youtube"
                label: "Video YouTube"
                widget: "object"
                fields:
                  - {label: "ID Video YouTube", name: "id", widget: "string"}
      - file: "content/titik-ba.md"
        label: "Halaman: Titik Ba"
        name: "halaman_titik_ba"
        fields:
          - {label: "Judul", name: "title", widget: "string"}
          - name: "body"
            label: "Konten Halaman (di bawah jargon)"
            widget: "list"
            types:
              - {name: "markdown", label: "Paragraf Teks", widget: "markdown"}
              - {name: "image", label: "Gambar", widget: "object", fields: [{label: "File Gambar", name: "src", widget: "image"}, {label: "Teks Alt", name: "alt", widget: "string"}, {label: "Keterangan", name: "caption", widget: "string", required: false}]}
              - {name: "youtube", label: "Video YouTube", widget: "object", fields: [{label: "ID Video YouTube", name: "id", widget: "string"}]}
      # Tambahkan file halaman utama lainnya (ayat-cerita.md, dll.) dengan pola yang sama di sini
      
  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal Publikasi", name: "date", widget: "datetime"}
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: false
        options: ["Titik Ba", "Ayat-Ayat Cerita", "Matematika Detik", "Matematika Titik", "Bimbel", "Kamp Santri"]
      - label: "Isi Artikel"
        name: "body"
        widget: "markdown"
        editor:
          styles:
            - {label: "Rata Kiri", value: "text-left"}
            - {label: "Rata Tengah", value: "text-center"}
            - {label: "Rata Kanan", value: "text-right"}
            - {label: "Rata Kiri-Kanan (Justify)", value: "text-justify"}