# Backend untuk testing lokal, tidak perlu akun GitHub.
# Nanti bisa diubah untuk dihubungkan ke GitHub.
backend:
  name: git-gateway
  branch: main 
# Lokasi penyimpanan media/gambar yang di-upload melalui CMS
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Halaman Tunggal & Gagasan"
    files:
      - file: "content/sejarah.md"
        label: "Halaman Sejarah"
        name: "sejarah"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-titik-ba.md"
        label: "Gagasan: Titik Ba"
        name: "gagasan_titik_ba"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-ayat-cerita.md"
        label: "Gagasan: Ayat-Ayat Cerita"
        name: "gagasan_ayat_cerita"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-matematika-detik.md"
        label: "Gagasan: Matematika Detik"
        name: "gagasan_matematika_detik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-matematika-titik.md"
        label: "Gagasan: Matematika Titik"
        name: "gagasan_matematika_titik"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-bimbel.md"
        label: "Gagasan: Bimbel"
        name: "gagasan_bimbel"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/gagasan-kamp-santri.md"
        label: "Gagasan: Kamp Santri"
        name: "gagasan_kamp_santri"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
      - file: "content/titik-ba.md"
        label: "Halaman: Titik Ba"
        name: "halaman_titik_ba"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
          - { label: "Link Halaman Gagasan", name: "gagasan_url", widget: "string", hint: "Contoh: /gagasan-titik-ba/" }
          - { label: "Teks Tombol 1", name: "cta_button_1_text", widget: "string" }
          - { label: "Teks Tombol 2", name: "cta_button_2_text", widget: "string" }
      # ... Tambahkan file halaman utama lainnya (Ayat Cerita, dll.) dengan pola yang sama ...

  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: false
        options: ["Titik Ba", "Ayat-Ayat Cerita", "Matematika Detik", "Matematika Titik", "Bimbel", "Kamp Santri"]
      - label: "Isi Artikel"
        name: "body"
        widget: "markdown"
        editor:
          styles:
            - { label: "Rata Kiri", value: "text-left" }
            - { label: "Rata Tengah", value: "text-center" }
            - { label: "Rata Kanan", value: "text-right" }
            - { label: "Rata Kiri-Kanan (Justify)", value: "text-justify" }
      - file: "content/kamp-santri.md"
        label: "Halaman Kamp Santri"
        name: "kamp_santri"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Teks Tombol 1", name: "cta_button_1_text", widget: "string" }
          - { label: "Teks Tombol 2", name: "cta_button_2_text", widget: "string" }
