backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pengaturan"
    label: "Pengaturan Halaman"
    files:
      - file: "content/_index.md"
        label: "Halaman Beranda"
        name: "beranda"
        fields:
          - {name: "body", label: "Konten Halaman", widget: "markdown", required: false}
          
  - name: "pages"
    label: "Halaman Utama"
    folder: "content/pages"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {name: "body", label: "Konten Halaman", widget: "markdown", required: false}

  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    identifier_field: "title"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal Publikasi", name: "date", widget: "datetime"}
      - {label: "Kategori", name: "categories", widget: "select", multiple: false, options: ["Titik Ba", "Ayat-Ayat Cerita", "Matematika Detik", "Matematika Titik", "Bimbel", "Kamp Santri"], required: false}
      - {name: "body", label: "Konten Artikel (Blok)", widget: "list", field: {label: "Paragraf", name: "paragraph", widget: "text"}, required: false}
        
  - name: "video"
    label: "Galeri Video"
    folder: "content/video"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    fields:
      - { label: "Judul Video", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "YouTube Video ID", name: "youtube_id", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown", required: false}