backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artikel"
    label: "Artikel"
    folder: "content/artikel"
    create: true
    identifier_field: "title"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal Publikasi", name: "date", widget: "datetime"}
      - label: "Kategori"
        name: "categories"
        widget: "select"
        multiple: false
        options: ["Titik Ba", "Ayat-Ayat Cerita", "Matematika Detik", "Matematika Titik", "Bimbel", "Kamp Santri"]
        required: false
      - name: "body"
        label: "Konten Artikel (Blok)"
        widget: "list"
        types:
          - {name: "markdown", label: "Paragraf Teks", widget: "object", fields: [{name: "content", label: "Teks", widget: "markdown"}]}
          - {name: "image", label: "Gambar", widget: "object", fields: [{label: "File Gambar", name: "src", widget: "image"}, {label: "Teks Alt", name: "alt", widget: "string"}, {label: "Keterangan", name: "caption", widget: "string", required: false}, {label: "Ukuran Gambar", name: "size", widget: "select", options: ["Kecil", "Sedang", "Besar"], default: "Sedang"}]}
          - {name: "youtube", label: "Video YouTube", widget: "object", fields: [{label: "ID Video YouTube", name: "id", widget: "string"}]}
        
  - name: "video"
    label: "Galeri Video"
    folder: "content/video"
    create: true
    identifier_field: "title"
    slug: "{{slug}}"
    fields:
      - { label: "Judul Video", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "YouTube Video ID", name: "youtube_id", widget: "string" }
      - { label: "Deskripsi", name: "body", widget: "markdown", required: false}